name = "MOID"
uuid = "368f1576-f431-425c-a571-9a7a59ebf91c"
keywords = ["astronomy"]
license = "MIT"
desc = "Compute Minimum Orbit Intersection Distances"
authors = ["Mike Kretlow <mikekretlow@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
